name: Export OpenKruise YAML
on:
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Install helm
        run: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Render kruise chart to YAML
        run: |
          helm template kruise https://github.com/openkruise/kruise/releases/download/v1.8.3/kruise-chart.tgz > 01-kruise.yaml
          helm template kruise-rollout https://github.com/openkruise/rollouts/releases/download/v0.6.2/kruise-rollout-chart.tgz >02-kruise-rollout.yaml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kruise-yaml
          path: "*.yaml"
